apiVersion: apps/v1
kind: Deployment
metadata:
  name: return-and-status-of-bank
  labels:
    app: return-and-status-of-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: return-and-status-of-bank
      version: v1
  template:
    metadata:
      labels:
        app: return-and-status-of-bank
        version: v1
    spec:
      containers:
      - name: return-and-status-of-bank
        image: nexus.devops.dvpoc.com.br/return-and-status-of-bank
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: cm-kafka-op
        - secretRef:
            name: sc-azure-data
---
apiVersion: v1
kind: Service
metadata:
  name: return-and-status-of-bank
spec:
  selector:
    app: return-and-status-of-bank
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: return-and-status-of-bank
spec:
  gateways:
    - default/default
  hosts:
  - return-and-status-of-bank.istio.dvpoc.com.br
  http:
  - name: "http-routes"
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: return-and-status-of-bank
        subset: v1
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: return-and-status-of-bank
spec:
  host: return-and-status-of-bank
  subsets:
  - name: v1
    labels:
      version: v1
